#creating an image from srcatch
FROM alpine:3.4

#MAINTANER romantia mali

RUN apk update

RUN echo "https//samtools.github.io/bcftools/ " 

RUN apk update bcftools-1.10.2.tar.bz2

COPY data/ /home/romantia/Desktop/Dockerfile/ 

cmd ["echo", "Large Scale Computing Systems and sciencetific programming"]
